library(dplyr)
library(jsonlite)
library(dplyr)
library(shiny)
library(httr)
library(devtools)
library(twitteR)
library(wordcloud)
library(randomcoloR)
library(RColorBrewer)
library(tm)

source('./server.R')
source('./ui.R')
source('./scripts/dm.R')
source('./scripts/getData.r')
source('./scripts/getWordCloud.r')

users <- c('@RealDonaldTrump', '@samsturtevant')

View(GetBig5DF(GetPredDF(GetData(users[1])), GetPredDF(GetData(users[2]))))
