library(dplyr)
library(jsonlite)
library(dplyr)
library(shiny)
library(httr)
library(devtools)
library(twitteR)
library(wordcloud)
library(randomcoloR)
library(RColorBrewer)
library(tm)

source('./server.R')
source('./ui.R')
source('./scripts/dm.R')
source('./scripts/getData.r')
source('./scripts/getWordCloud.r')

users <- c('@RealDonaldTrump', '@samsturtevant')

spider_data <- GetBig5DF(GetPredDF(GetData(users[1])), GetPredDF(GetData(users[2])))
other_data1 <- GetOtherDF(GetPredDF(GetData(users[1])), GetIntDF(GetData(users[1])))
other_data2 <- GetOtherDF(GetPredDF(GetData(users[2])), GetIntDF(GetData(users[2])))